### ISSUE TITLE
Get this into official netty?

### ISSUE THREAD

**Issue by anton-johansson** [Ziver/Netty-Transport-jSerialComm#1]
Do you think it would be possible to get this code directly into [netty](https://github.com/netty/netty), as a replacement for the deprecated [netty-transport-rxtx](https://github.com/netty/netty/tree/4.1/transport-rxtx)?

**Comment by Ziver** [comment]
Hi,
The reason for the depreciation of rxtx was actually this code, the Netty developers did not want this in the repo as it is hard to do unit testing on code that was requiring a serial port.

Reference: https://github.com/netty/netty/pull/7198

**Comment by anton-johansson** [comment]
Ok, that makes sense. Thanks!

**Comment by Ziver** [comment]
Btw, sorry for the very late response, did not have notifications on.
