### ISSUE TITLE
Is this project not maintained?

### ISSUE THREAD

**Issue by fengyuanhui** [Ziver/Netty-Transport-jSerialComm#3]
Is this project not maintained?

**Comment by Ziver** [comment]
I would say Yes, it is no longer actively being worked on. I do not have any projects depending on Netty-Transport-jSerialComm so it is quite difficult for me to make any meaningful changes.

But I still do accept pull request and are open to if anybody would be willing to take the project over and actively work on it.

**Comment by fengyuanhui** [comment]
I hope this project will continue.This is because it is the only serial communication project that is still being maintained.Netty officials did not include jSerialComm in support.So the Netty-transport-JSerialComm project is Netty's only hope in serial communication.
